version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    # See: http://www.tocker.ca/2014/03/10/configuring-mysql-to-use-minimal-memory.html
    # See: https://hub.docker.com/_/mysql/
    command: --innodb_buffer_pool_size=10M
             --innodb_log_buffer_size=256K
             --query_cache_size=0
             --key_buffer_size=8
             --thread_cache_size=0
             --host_cache_size=0
             --innodb_ft_cache_size=1600000
             --innodb_ft_total_cache_size=32000000
             --max_allowed_packet=16777216
             --default-time-zone='+00:00'
             --init-file /app/init.sql
    volumes:
      - ./init.sql:/app/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
